# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 36d82b2635a058b0426fbf54689ea110beadd5a3cbc85a0ee17fe59f5c0e65c6c703872e9a15699a38ef77fbd781a58e5a9f83988324f912cd905f3f1d96417c

test:
  secret_key_base: a5fcbc781609665fe6d5d645caf0e276dae6f0eaa97a5c33cdc871ad12abe9fbfd898b4835623c29ccd64146fdc73650a80e0821eecbdb24570b2108414d8e35

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
